sudo: required

language: cpp

services:
  - docker

env:
  global:
    - toolset_branch: master
    - ros_release: kinetic
    - ubuntu_version: xenial
    - docker_image: "shadowrobot/build-tools:$ubuntu_version-$ros_release"
    - used_modules: check_build,software_tests,codecov_tool #check_cache,code_style_check,check_deb_make,codecov_tool
    # available modules: https://github.com/shadow-robot/sr-build-tools/blob/master/ansible/roles/ci/doc/modules.md

before_install:
  # pull docker image from shadowrobot
  #- docker pull $docker_image
  
script:
# get CI-environment for codecov
# run docker image from shadowrobot in ansible working directory and and with travis build dir as mounted volume
# bash command to run in docker container consists of
#   - download ximea drivers  
#   - extract ximea drivers
#   - remove udevadm command in ximea install script (because it does not work in the docker container)
#   - auto approval of firewire camera warning in ximea install script
#   - install ximea drivers
#   - pull latest ansible playbook files from sr robotics
#   - checkout correct branch
#   - run ansible playbook with provided parameters
  - >
      ci_env=`bash <(curl -s https://codecov.io/env)` && echo $ci_env && echo $CODECOV_ENV && echo $CI_BUILD_ID && echo test
