sudo: required

language: cpp

services:
  - docker

env:
  global:
    - toolset_branch: master
    - ros_release: kinetic
    - ubuntu_version: xenial
    - docker_image: "shadowrobot/build-tools:$ubuntu_version-$ros_release"
    - used_modules: check_build #check_cache,code_style_check,check_deb_make,codecov_tool
    - docker_user_home: '/home/user'

before_install:
  - docker pull $docker_image
  
script:
  - >
      docker run -w "$docker_user_home/sr-build-tools/ansible" -v $TRAVIS_BUILD_DIR:/host$TRAVIS_BUILD_DIR 
      $docker_image 
      bash -c "wget http://www.ximea.com/downloads/recent/XIMEA_Linux_SP.tgz; 
               tar xzf XIMEA_Linux_SP.tgz; 
               cd package; 
               sed -i -e 's/udevadm control --reload/echo removed command/g' scripts/install_steps; 
               sed -i -e 's/read choice/echo automatic approval/g' scripts/install_steps; 
               ./install; 
               cd ..;
               git pull &&
               git checkout $toolset_branch &&
               sudo PYTHONUNBUFFERED=1 ansible-playbook -v -i \"localhost,\" -c local docker_site.yml --tags \"travis,$used_modules\" -e \"travis_repo_dir=/host$TRAVIS_BUILD_DIR  travis_is_pull_request=$TRAVIS_PULL_REQUEST ros_release=$ros_release ubuntu_version_name=$ubuntu_version\"" 
