ci:
  - travis-ci.org
  
ignore:
  - "*.launch" # ros launch files
  - "*.test" # ros test files
  - "*.msg" # ros msg files
  - "*.yml" # yml files
  - "*.md" # md files
  - "*.xml" # xml files

# fix path in Travis-CI
fixes:
  - "src/host/home/travis/build/tum-phoenix/drive_ros_config/::"
